### ISSUE TITLE
Feature Request for Browser to Integrate with Download Managers

### ISSUE THREAD

**Issue by TrueHOOHA** [Slion/Fulguris#648] opened 2024-07-16 07:50 UTC
I am reaching out to request a feature enhancement for fulgrius that I believe would significantly improve the user experience for many of us.
Currently, I often find myself needing to download large files or manage multiple downloads efficiently. To do this, I rely on advanced download managers such as Advanced Download Manager (ADM) or 1dm. However, the integration between these tools and fulgrius is not seamless, which can be quite inconvenient.
Feature Request: I would like to propose the implementation of a feature that allows fulgrius to automatically detect and utilize download managers like ADM or 1DM when initiating file downloads. 
Prompt users to select their preferred download manager during the first setup or through settings.
Automatically route download requests to the selected download manager when a file is to be downloaded.

**Comment by Slion** [comment] 2024-07-18 07:38
Duplicate of #422.

**Closed by Slion** 2024-07-18 07:38 UTC
Labels: feature, download
