### ISSUE TITLE
the ability to automatically reject "open in another application" offers

### ISSUE THREAD

**Issue by Wjxfi** [Slion/Fulguris#494] opened 2023-07-11 17:22 UTC
https://www.f-droid.org/packages/com.trianguloy.urlchecker/
After installing this app, every time I tab in, I am constantly asked if I want to open this site in another app. This is incredibly annoying.

add a toggle. It will remove the automatic question and add a "ask" button in the "main menu" about it.

screenshot:
![8251865c-48ac-48cf-8c9e-380266d74d6a.jpg](https://github.com/Slion/Fulguris/assets/113500363/271db4cc-5410-4806-a4a0-bc04f14d55f9)

**Comment by Slion** [comment] 2023-07-11 20:13
This will be fixed as part of #159

**Closed by Slion** 2023-07-11 20:13 UTC
Labels: duplicate

**Comment by Slion** [comment] 2023-07-18 20:09
Also a duplicate of #138
