### ISSUE TITLE
feat: external download manager

### ISSUE THREAD

**Issue by ZhymabekRoman** [Slion/Fulguris#614] opened 2024-03-23 18:49 UTC
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when downloading large files from the internet, as the download process can be interrupted by various factors such as network instability or the expiration of download links. This leads to the need to restart the download from the beginning, wasting time and bandwidth.

**Describe the solution you'd like.**

I would like to see an external download manager functionality integrated into the browser. This feature would allow users to delegate download tasks to an external download manager, such as DVGet or ADM. The browser would send the download link to the external download manager, which would handle the download process. This solution would be particularly useful for large files, as it would enable resuming downloads from where they left off, even if the download link expires.

**Comment by Slion** [comment] 2024-03-24 20:54
Duplicate of #422.

**Closed by Slion** 2024-03-24 20:54 UTC
Labels: duplicate, feature

**Comment by Slion** [comment] 2024-03-31 06:30
This might already be working actually. Just long press your download link and share it with your downloader app. Let me know if it does the job.
