### ISSUE TITLE
Dependency Not Found - Due to JCenter Migration

### ISSUE THREAD

**Issue by Justlike48** [Slion/Fulguris#655] opened 2024-10-28 23:28 UTC
It seems these dependencies—permissions:1.1.2, mezzanine:1.1.1, and netcipher-webkit:2.0.0-alpha1—are no longer available at their original locations.

**### Could not find permissions-1.1.2.aar (com.anthonycr.grant:permissions:1.1.2).
Searched in the following locations:
https://plugins.gradle.org/m2/com/anthonycr/grant/permissions/1.1.2/permissions-1.1.2.aar

Could not find mezzanine-1.1.1.jar (com.anthonycr.mezzanine:1.1.1).
Searched in the following locations:
https://plugins.gradle.org/m2/com/anthonycr/mezzanine/mezzanine/1.1.1/mezzanine-1.1.1.jar

Could not find netcipher-webkit-2.0.0-alpha1.jar (info.guardianproject.netcipher:netcipher-webkit:2.0.0-alpha1).
Searched in the following locations:
https://plugins.gradle.org/m2/info/guardianproject/netcipher/netcipher-webkit/2.0.0-alpha1/netcipher-webkit-2.0.0-alpha1.jar**

Additionally, as JCenter (a popular Maven repository) has been deprecated and replaced, some dependencies might need to be relocated or bundled directly into the project. This situation is affecting the build and preventing the APK from being processed correctly.

Request for Assistance:
Could you kindly:

Provide alternative sources or updated dependencies, or
Update the APK with these dependencies bundled locally in the libs directory?
This would help ensure the APK can be built and maintained correctly moving forward. If there are any other changes I should be aware of due to the JCenter migration, please let me know.

Your assistance is greatly appreciated. Thank you in advance, and I look forward to your response.

**Comment by sampatsharma143** [comment] 2024-11-24 14:18
Have you found any solutions ?

**Comment by Slion** [comment] 2024-11-24 20:05
Duplicate of #650.

**Closed by Slion** 2024-11-24 20:05 UTC
