### ISSUE TITLE
Tab and URL Bar titles are sometimes out of sync

### ISSUE THREAD

**Issue by Zero3K** [Slion/Fulguris#234] opened 2021-07-28 15:43 UTC
# Description
The Tab and URL Bar titles are sometimes out of sync (in other words, they do not match each other)

# Environment
 - Device: Lenovo TB-X505F
 - OS: Android 10
 - Version: 1.6.12

# To reproduce
Steps to reproduce the behaviour:
1. Go to https://jira.reactos.org/browse/CORE-17710?jql=ORDER%20BY%20updated%20DESC%2C%20lastViewed%20ASC
2. Tap on another issue in the left frame.

# Expected behaviour
The title shown in the URL Bar should match the one shown in the Tab Bar.

**Comment by Slion** [comment] 2021-07-28 16:01
I'm going to assume this is a duplicate of #195

**Closed by Slion** 2021-07-28 16:01 UTC
Labels: bug

**Comment by Zero3K** [comment] 2021-07-28 17:08
It is.
