### ISSUE TITLE
Opt-out check for updates

### ISSUE THREAD

**Issue by IzK666** [Slion/Fulguris#546] opened 2023-09-02 09:19 UTC
Can you implement an easier way to disable update checks?
As you know (you've made a comment in the code), the popup is really disturbing and I'm not interested on being notified everytime I open the app just to know that you updated some translations (which many people will like, of course, but not me).

BTW: Although my critisism about this missing and IMHO important feature, I like your browser for it's simplicity, and all the features it offers ;)

**Comment by Slion** [comment] 2023-09-02 09:59
Duplicate of #88

**Closed by Slion** 2023-09-02 09:59 UTC
Labels: duplicate, feature
