### ISSUE TITLE
Bottom sheet for tabs navigation

### ISSUE THREAD

**Issue by RanbirSingh** [Slion/Fulguris#142] opened 2021-01-22 23:39 UTC
Hi there thanks for this fast and lightweight browser.
Bottomsheet navigation for tabs like firefox that would provide Nice user experience also we can use that with bookmarks Also..

**Comment by Slion** [comment] 2021-01-23 00:09
I'm not sure I fully understand. Could you develop your idea some more? Do you have screenshots?

**Comment by RanbirSingh** [comment] 2021-01-23 00:14
![Screenshot_2021-01-23-05-40-59-910_org mozilla firefox](https://user-images.githubusercontent.com/13647384/105561798-e0276b00-5d3d-11eb-8d02-8ae7b3949d59.jpg)

as of now we are using side navigation that is bit old concept and bit difficult to navigate but with bottom sheet it will be much easier to navigate

**Comment by Slion** [comment] 2021-01-23 00:33
I see, thanks. I just tried it quick on Firefox. It's basically the tool bar at the bottom. The direction from which the tab list opens is not so relevant. Moreover you need two swipes to the bottom to close it or just one swipe when using the back gesture which then the same in Fulguris.
Bottom bar is often requested so it will be available sooner or later.

Thanks for those great ideas!

**Comment by Slion** [comment] 2021-01-23 00:39
Closing as duplicate of #43. Feel free to keep discussing that matter here though.

**Closed** 2021-01-23 00:40 UTC
Labels: duplicate, feature
