### ISSUE TITLE
Scrollbars don't scroll (can't be dragged)

### ISSUE THREAD

**Issue by pezcurrel** [Slion/Fulguris#653] opened 2024-09-27 21:00 UTC
# Description
Even after setting the scrollbars to their maximum size and disabling their fading, they are not draggable, so one can't scroll the webpage with them.

# Environment
 - Device: Nokia TA-1535
 - OS: Android 12
 - Version: Fulguris v1.9.30

**Comment by Slion** [comment] 2024-09-28 02:51
Duplicate of #497.
See: https://github.com/Slion/Fulguris/issues/497#issuecomment-1692765740

**Closed by Slion** 2024-09-28 02:51 UTC
Labels: bug, duplicate
