### ISSUE TITLE
Swipe on tab bar to change tap, swipe left to create new tab

### ISSUE THREAD

**Issue by PalmTamino** [Slion/Fulguris#512] opened 2023-07-30 20:17 UTC
I'd like to have a toolbar like on Safari iOS, if there's no new tab to the right, I can swipe from right to left, in order to create a new tab. I can also swipe from left to right, to hop between the other tabs

All like Safari.

There's no browser on android having this, right? I really want this.

**Comment by Slion** [comment] 2023-07-30 20:22
Duplicate of #450
Feel free to join the conversation over there.

**Closed by Slion** 2023-07-30 20:22 UTC
Labels: duplicate, feature
