### ISSUE TITLE
On some pages, you can't go back and it becomes refreshed

### ISSUE THREAD

**Issue by chwt163** [Slion/Fulguris#459] opened 2023-05-09 10:18 UTC
For example, these pages:
https://www.mydrivers.com/
https://www.ithome.com/
Once these two URLs are open, you can't go back unless you quickly click back twice.
The experience is really bad, I hope Fulguris can improve.

**Comment by Slion** [comment] 2023-05-10 09:23
Duplicate of #414

**Closed by Slion** 2023-05-10 09:23 UTC
Labels: bug, duplicate

**Comment by chwt163** [comment] 2024-04-04 04:48
The Einkbro browser solves this problem, can developers refer to it?
https://github.com/plateaukao/einkbro
