### ISSUE TITLE
Cannot load any webpage

### ISSUE THREAD

**Issue by Cwpute** [Slion/Fulguris#571] opened 2023-10-11 23:09 UTC
# Description
Since i downloaded Fulguris 1.9.15, i can't acces any webpage. The laoding starts them stops at around 15%, and never loads anymore and i'm stuck with a black page. I've been forced to install the previous Fulguris version 1.9.14to browse the internet again.

Never had such a huge problem before.

# Environment
 - Device: Nokia TA-1157
 - OS: Android11
 - Version: 1.9.15

**Comment by Slion** [comment] 2023-10-12 00:52
Could it be #565?

Can you try v1.9.17?

**Comment by smith901** [comment] 2023-10-12 01:37
OS:  Android 13
Ver: 1.9.15

## What I did 
Came to check for this issue and read #565. F-Droid latest version is 1.9.15 with no updates as of posting.    
Turned animations on & pages loaded.     
Turned animations off then changed to another tab with a previously accesed website. Old tab's page still shows and is scrollable. Page never finish loading.    
Try to go back to 1st tab, app crashes.

**Comment by GameOverFlowChart** [comment] 2023-10-12 04:19
Yup, I updated the app with F-droid to 1.9.15 and now I have the same problem. What makes this worse is that this did happen before #537 was implemented which is needed exactly for this kind of worst case scenarios.

**Comment by Slion** [comment] 2023-10-12 05:47
Can you guys confirm this issue is a duplicate of #565 ? If that's the case turning on animations should fix it. Once you update to 1.9.17 you should be able to turn off animations again.

**Comment by GameOverFlowChart** [comment] 2023-10-12 05:52
> Can you guys confirm this issue is a duplicate of #565 ? If that's the case turning on animations should fix it. Once you update to 1.9.17 you should be able to turn off animations again.

Yes tab switch animations fix it

**Comment by Cwpute** [comment] 2023-10-12 06:47
I can confirm this too. Sorry for the duplicate issue.

**Comment by Slion** [comment] 2023-10-13 15:28
I've updated the [release channels documentation](https://github.com/Slion/Fulguris/blob/main/README.md#release-channels) to make it clearer what to expect from each channels.

**Closed by Slion** 2023-10-13 15:28 UTC
Labels: bug, duplicate, fixed
