### ISSUE TITLE
Randomly lost all sessions and pages

### ISSUE THREAD

**Issue by theriel** [Slion/Fulguris#399] opened 2022-10-01 05:38 UTC
# Description
I use the browser for reading stories on royalroad.com, so I was using it before going to bed. I woke up this morning to find that all sessions were cleared with zero saved pages, including the one I was currently using. The labels still exist, but they're useless if nothing is saved in them. History still exists, as do bookmarks. 

# Environment
 - Device: Oneplus 7 Pro 
 - OS: Android 11, Oxygen OS 11.0.9.1
 - Version: 1.8.8
 - Webview version: com.google.android.webview (105.0.5195.136/519513634)

# To reproduce
I have no idea how to reproduce this. It happened overnight when I was not interacting with the phone. When I went to bed everything was fine. I can check whatever log is relevant, but there were no crashes. 

This is a pretty high priority bug, so happy to help out however I can. It ruins the point of saving things if all sessions are deleted, and probably would make some people change browsers.

**Comment by Slion** [comment] 2022-10-03 09:44
This one has been with us for a long time and is somewhat related to #193.
Hopefully all you lost is the list of sessions. Not the sessions themselves.
Just switch to your sessions and see that their content is still there. The tab count will show up again in the sessions list after you open a session.

**Comment by Slion** [comment] 2022-10-05 21:50
@theriel Could you confirm that you have in fact not lost all your sessions but just the session list?

**Comment by theriel** [comment] 2022-10-06 06:08
I don't know what terminology you're using. I lost the list of tabs on my
active session, and none of the sessions showed the number of tabs; by
clicking the name of the session, however, all the tabs came back, as did
the numbers.

I'd say you can mark this as a duplicates of the one you mentioned and
close it out. I'm fairly sure that it's the same issue.

The only thing that I'm not sure about is whether tabs are still saved if
someone didn't save their session. Default had nothing saved in it.

**Comment by Slion** [comment] 2022-10-06 07:13
>  I lost the list of tabs on my
active session, and none of the sessions showed the number of tabs; by
clicking the name of the session, however, all the tabs came back, as did
the numbers.

Thanks that's all I needed to know. I'll close it as a duplicate of #193 then.

**Closed by Slion** 2022-10-06 07:13 UTC
Labels: bug, user request
